macos_min_version:
  - 10.12 # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:
  - 10.12 # [osx and x86_64]
CONDA_BUILD_SYSROOT:
  - /opt/MacOSX10.12.sdk        # [osx and x86_64]
rust_compiler_version:
  - '1.79.0'
