{% set name = "tsdownsample" %}
{% set version = "0.1.5.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e597d6f1891f8163d9425b5f71759bfb17e3545ab72618d7ebaae0356e702829
  patches:
    # 95 | #![cfg_attr(feature = "nightly_simd", feature(avx512_target_feature))]
    # |                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    # error[E0554]: #![feature] may not be used on the stable release channel
    - patches/0001-update-argminmax.patch

build:
  number: 0
  skip: true  # [py<38]
  script_env:
    - PYO3_USE_ABI3_FORWARD_COMPATIBILITY=1
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - pip
    - python
    - maturin >=1.1,<2.0
  run:
    - python
    - numpy

test:
  source_files:
    - tests
  imports:
    - tsdownsample
  commands:
    - pip check
    - pytest tests --ignore="tests/benchmarks"
  requires:
    - pip
    - pytest
    - pytest-rerunfailures

about:
  home: https://github.com/predict-idlab/tsdownsample
  license: MIT
  license_file:
    - LICENSE
    - downsample_rs/LICENSE
  license_family: MIT
  summary: Time series downsampling in Rust
  description: |
    High-performance time series downsampling algorithms for visualization
  dev_url: https://github.com/predict-idlab/tsdownsample
  doc_url: https://github.com/predict-idlab/tsdownsample/blob/main/README.md

extra:
  recipe-maintainers:
    - thewchan
