{% set name = "tsdownsample" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/tsdownsample-{{ version }}.tar.gz
  sha256: 5268d0ab5e8572138871feff389440a0c59d5e0fe02c0fa1cf975d74ba33b933
  patches:
    - update-argminmax.patch

build:
  # maturin 0.14.x isn't available for python 3.12
  skip: true  # [py<37 or py>=312 or win]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - patch
  host:
    - python
    - maturin >=0.14,<0.15
    - pip
  run:
    - python
    - numpy
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx and x86_64]

test:
  source_files:
    - tests
  imports:
    - tsdownsample
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-cov
    - pytest-benchmark

about:
  home: https://github.com/predict-idlab/tsdownsample
  dev_url: https://github.com/predict-idlab/tsdownsample
  doc_url: https://github.com/predict-idlab/tsdownsample/blob/main/README.md
  summary: Time series downsampling in Rust
  description: |
    High-performance time series downsampling algorithms for visualization
  license: MIT
  license_file:
    - LICENSE
    - downsample_rs/LICENSE
  license_family: MIT

extra:
  recipe-maintainers:
    - thewchan
